## Preliminary Data Exploration and Data Cleaning with Pandas

In [2]:
import pandas as pd
df = pd.read_csv("data/salaries_by_college_major.csv")

In [3]:
df.head()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
0,Accounting,46000.0,77100.0,42200.0,152000.0,Business
1,Aerospace Engineering,57700.0,101000.0,64300.0,161000.0,STEM
2,Agriculture,42600.0,71900.0,36300.0,150000.0,Business
3,Anthropology,36800.0,61500.0,33800.0,138000.0,HASS
4,Architecture,41600.0,76800.0,50600.0,136000.0,Business

In [4]:
len(df)

51

In [5]:
len(df.index)

51

In [6]:
df.shape

(51, 6)

In [7]:
df.columns

Index(['Undergraduate Major', 'Starting Median Salary',
       'Mid-Career Median Salary', 'Mid-Career 10th Percentile Salary',
       'Mid-Career 90th Percentile Salary', 'Group'],
      dtype='object')

### Missing Values and Junk Data

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51 entries, 0 to 50
Data columns (total 6 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Undergraduate Major                51 non-null     object
 1   Starting Median Salary             50 non-null     float64
 2   Mid-Career Median Salary           50 non-null     float64
 3   Mid-Career 10th Percentile Salary  50 non-null     float64
 4   Mid-Career 90th Percentile Salary  50 non-null     float64
 5   Group                              50 non-null     object
dtypes: float64(4), object(2)
memory usage: 2.5+ KB

In [10]:
df.tail()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
46,Psychology,35900.0,60400.0,31600.0,127000.0,HASS
47,Religion,34100.0,52000.0,29700.0,96400.0,HASS
48,Sociology,36500.0,58200.0,30700.0,118000.0,HASS
49,Spanish,34000.0,53100.0,31000.0,96400.0,HASS
50,Source: PayScale Inc.,NaN,NaN,NaN,NaN,NaN

In [11]:
df.isna().tail()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
46,False,False,False,False,False,False
47,False,False,False,False,False,False
48,False,False,False,False,False,False
49,False,False,False,False,False,False
50,False,True,True,True,True,True

In [12]:
clean_df = df.dropna()
clean_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 50 entries, 0 to 49
Data columns (total 6 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Undergraduate Major                50 non-null     object
 1   Starting Median Salary             50 non-null     float64
 2   Mid-Career Median Salary           50 non-null     float64
 3   Mid-Career 10th Percentile Salary  50 non-null     float64
 4   Mid-Career 90th Percentile Salary  50 non-null     float64
 5   Group                              50 non-null     object
dtypes: float64(4), object(2)
memory usage: 2.7+ KB

In [13]:
clean_df.tail()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
45,Political Science,40800.0,78200.0,41200.0,168000.0,HASS
46,Psychology,35900.0,60400.0,31600.0,127000.0,HASS
47,Religion,34100.0,52000.0,29700.0,96400.0,HASS
48,Sociology,36500.0,58200.0,30700.0,118000.0,HASS
49,Spanish,34000.0,53100.0,31000.0,96400.0,HASS

In [14]:
max_median_salary = clean_df['Starting Median Salary'].max()
clean_df[max_median_salary == clean_df['Starting Median Salary']]

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
43,Physician Assistant,74300.0,91700.0,66400.0,124000.0,STEM

In [15]:
clean_df['Starting Median Salary'].idxmax()

43

In [16]:
clean_df['Undergraduate Major'].loc[43]

'Physician Assistant'

In [17]:
clean_df['Undergraduate Major'][43]

'Physician Assistant'

In [18]:
clean_df.loc[43]

Undergraduate Major                  Physician Assistant
Starting Median Salary                           74300.0
Mid-Career Median Salary                         91700.0
Mid-Career 10th Percentile Salary                66400.0
Mid-Career 90th Percentile Salary               124000.0
Group                                               STEM
Name: 43, dtype: object

In [19]:
clean_df.loc[clean_df['Mid-Career Median Salary'].idxmax()]['Undergraduate Major']

'Chemical Engineering'

In [20]:
clean_df.loc[clean_df['Starting Median Salary'].idxmin(), ['Undergraduate Major', 'Starting Median Salary']]

Undergraduate Major       Spanish
Starting Median Salary    34000.0
Name: 49, dtype: object

In [21]:
clean_df.iloc[clean_df['Starting Median Salary'].idxmin(), [0,1]]

Undergraduate Major       Spanish
Starting Median Salary    34000.0
Name: 49, dtype: object

In [22]:
# clean_df.iloc[clean_df['Starting Median Salary'].idxmin()][['Undergraduate Major', 'Starting Median Salary']]
selected_columns = ['Undergraduate Major', 'Starting Median Salary']
clean_df.loc[clean_df['Starting Median Salary'].idxmin()][selected_columns]

Undergraduate Major       Spanish
Starting Median Salary    34000.0
Name: 49, dtype: object

In [23]:
selected_columns = ['Undergraduate Major', 'Starting Median Salary']
clean_df.loc[clean_df['Mid-Career Median Salary'].idxmin()][selected_columns]

Undergraduate Major       Education
Starting Median Salary      34900.0
Name: 18, dtype: object

### Highest and Lowest Degrees

In [25]:
print(clean_df['Mid-Career Median Salary'].max())
print(f"Index for the max mid career salary: {clean_df['Mid-Career Median Salary'].idxmax()}")
clean_df['Undergraduate Major'][8]

107000.0
Index for the max mid career salary: 8

'Chemical Engineering'

In [26]:
print(clean_df['Starting Median Salary'].min())
clean_df['Undergraduate Major'].loc[clean_df['Starting Median Salary'].idxmin()]

34000.0

'Spanish'

### Sorting Values & Adding Columns: Majos with Most Potential vs Lowest Risk

In [28]:
clean_df.head()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
0,Accounting,46000.0,77100.0,42200.0,152000.0,Business
1,Aerospace Engineering,57700.0,101000.0,64300.0,161000.0,STEM
2,Agriculture,42600.0,71900.0,36300.0,150000.0,Business
3,Anthropology,36800.0,61500.0,33800.0,138000.0,HASS
4,Architecture,41600.0,76800.0,50600.0,136000.0,Business

In [29]:
(clean_df['Mid-Career 90th Percentile Salary'] - clean_df['Mid-Career 10th Percentile Salary']).head()

0    109800.0
1     96700.0
2    113700.0
3    104200.0
4     85400.0
dtype: float64

In [30]:
(clean_df['Mid-Career 90th Percentile Salary'].subtract(clean_df['Mid-Career 10th Percentile Salary'])).head()

0    109800.0
1     96700.0
2    113700.0
3    104200.0
4     85400.0
dtype: float64

In [31]:
spread_col = clean_df['Mid-Career 90th Percentile Salary'] - clean_df['Mid-Career 10th Percentile Salary']
clean_df.insert(1, 'Spread', spread_col)
clean_df.head()

,Undergraduate Major,Spread,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
0,Accounting,109800.0,46000.0,77100.0,42200.0,152000.0,Business
1,Aerospace Engineering,96700.0,57700.0,101000.0,64300.0,161000.0,STEM
2,Agriculture,113700.0,42600.0,71900.0,36300.0,150000.0,Business
3,Anthropology,104200.0,36800.0,61500.0,33800.0,138000.0,HASS
4,Architecture,85400.0,41600.0,76800.0,50600.0,136000.0,Business

In [32]:
low_risk = clean_df.sort_values('Spread')

In [33]:
low_risk[['Undergraduate Major', 'Spread']].head()

           Undergraduate Major   Spread
40                     Nursing  50700.0
43         Physician Assistant  57600.0
41                   Nutrition  65300.0
49                     Spanish  65400.0
27  Health Care Administration  66400.0

Does `.sort_values()` sort in ascending or descending order? To find out, check out the Pandas documentation: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.sort_values.html

You can also bring up the quick documentation with **shift + tab** on your keyboard directly in the Python notebook.

### Degrees with the Highest Potential

In [35]:
# Majors with the Highest Potential
highest_potential = clean_df.sort_values('Mid-Career 90th Percentile Salary', ascending=False)
highest_potential[['Undergraduate Major', 'Mid-Career 90th Percentile Salary']].head()

     Undergraduate Major  Mid-Career 90th Percentile Salary
17             Economics                           210000.0
22               Finance                           195000.0
8   Chemical Engineering                           194000.0
37                  Math                           183000.0
44               Physics                           178000.0

In [36]:
# Majors with the Greatest Spread in Salaries
highest_spread = clean_df.sort_values('Spread', ascending=False)
highest_spread[['Undergraduate Major', 'Spread']].head()

   Undergraduate Major    Spread
17           Economics  159400.0
22             Finance  147800.0
37                Math  137800.0
36           Marketing  132900.0
42          Philosophy  132500.0

In [37]:
highest_spread = clean_df.sort_values('Mid-Career Median Salary', ascending=False)
highest_spread[['Undergraduate Major', 'Spread', 'Mid-Career Median Salary']].head()

       Undergraduate Major    Spread  Mid-Career Median Salary
8     Chemical Engineering  122100.0                  107000.0
12    Computer Engineering   95900.0                  105000.0
19  Electrical Engineering   98700.0                  103000.0
1    Aerospace Engineering   96700.0                  101000.0
17               Economics  159400.0                   98600.0

### Grouping and Pivoting Data with Pandas

In [39]:
clean_df.groupby('Group').count()

,Undergraduate Major,Spread,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary
Group,,,,,,
Business,12,12,12,12,12,12
HASS,22,22,22,22,22,22
STEM,16,16,16,16,16,16

In [40]:
group_mean = clean_df.iloc[:, 1:].groupby('Group').mean()
group_mean

,Spread,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary
Group,,,,,
Business,103958.333333,44633.333333,75083.333333,43566.666667,147525.000000
HASS,95218.181818,37186.363636,62968.181818,34145.454545,129363.636364
STEM,101600.000000,53862.500000,90812.500000,56025.000000,157625.000000

In [41]:
pd.options.display.float_format = '{:,.2f}'.format
group_mean

,Spread,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary
Group,,,,,
Business,"103,958.33","44,633.33","75,083.33","43,566.67","147,525.00"
HASS,"95,218.18","37,186.36","62,968.18","34,145.45","129,363.64"
STEM,"101,600.00","53,862.50","90,812.50","56,025.00","157,625.00"

The PayScale dataset used in this lesson was from 2008 and looked at the prior 10 years. Notice how Finance ranked very high on post-degree earnings at the time. However, we all know there was a massive financial crash in that year. Perhaps things have changed. We can use what we have learnt about web scraping in the prior lessons (e.g., Day 45) and update information from [PayScale's website](https://www.payscale.com/research/US/Country=United_States/Salary).

### Learning Points & Summary
- Use `.head()`, `.tail()`, `.shape` and `.columns` to explore your DataFrame and find out the number of rows and columns as well as the column names.
- Look for NaN (not a number) values with `.findna()` and consider using `.dropna()` to clean up your DataFrame.
- You can access entire columns of a DataFrame using the square bracket notation: `df['column name']` or `df[['column name 1', 'column name 2', 'column name 3']]`.
- You can access individual cells in a DataFrame by chaining square brackets `df['column name'][index]` or using `df['column name'].loc[index]`.
- The largest and smallest values, as well as their positions, can be found with methods like `.max()`, `.min()`, `.idxmax()` and `idxmin()`.
- You can sort the DataFrame with `.sort_values()` and add new columns with `.insert()`.
- To create an Excel Style Pivot Table by grouping entries that belong to a particular category use the `.groupby()` method.

### Cheat Sheet
#### Most-used Python Commands for Data Cleaning
1. Data Inspection
```python
df.head()     # Shows first rows of DataFrame
df.info()     # Displays DataFrame info and data types
df.describe() # Shows summary statistics of numeric columns
```
2. Missing Data Handling
```python
df.isnull().sum() # Counts null values per column
df.dropna()       # Remove rows with missing values
df.fillna(value)  # Replace missing values with specified value
```
3. Data Cleaning & Transformation
```python
df.drop_duplicates()              # Remove duplicate rows from DataFrame
df.rename(columns={'old': 'new'}) # Rename columns using dictionary mapping
df.astype({'col': 'type'})        # Convert column data types
df.replace(['old'], ['new'])      # Replace values in DataFrame
df.reset_index()                  # Reset index to default numeric sequence
df.drop(['col'], axis=1)          # Removes specified columns
```
4. Data Selection & Filtering
```python
df.loc('label', 'col') # Selects data by labels/conditions
df.iloc[]              # Access data using integer positions
df[df['col'] > value]  # Filters rows based on condition
```
5. Data Aggregation & Analysis
```python
df.groupby('col').agg('mean')          # Groups and applies aggregation function
df.sort_values('col', ascending=False) # Orders data by column values
df.value_counts()                      # Count unique values in a column
df.apply()                             # Apply function to rows/columns
df.pivot_table(values, index, columns) # Creates pivot table from data
```
6. Data Combining/Merging
```python
df.concat([df1, df2])        # Concatenates multiple DataFrames
df.merge(df1, fd2, on='key') # Merges two DataFrames on a key column
df1.join(df2)                # Joins DataFrames on index
df1.append(df2)              # Appends rows of df2 to df1
```