# **Day 25**
## CSV Data and the Pandas Library

### Read csv data file with csv library

In [3]:
import csv

with open("data/weather_data.csv") as data_file:
    data = csv.reader(data_file)

    temperatures = []

    for row in data:
        if row[1] != "temp":
            temperatures.append(int(row[1]))

    print(temperatures)

[12, 14, 15, 14, 21, 22, 24]

### Pandas library

#### DataFrames and Series: Working with Rows and Columns

#### Pandas documentation: https://pandas.pydata.org/docs/
#### Pandas API Reference: https://pandas.pydata.org/docs/reference/index.html

In [7]:
import pandas as pd

data = pd.read_csv("data/weather_data.csv")

In [8]:
# Pandas works with DataFrames and Series
type(data)

pandas.core.frame.DataFrame

In [9]:
data

         day  temp condition
0     Monday    12     Sunny
1    Tuesday    14      Rain
2  Wednesday    15      Rain
3   Thursday    14    Cloudy
4     Friday    21     Sunny
5   Saturday    22     Sunny
6     Sunday    24     Sunny

In [10]:
# Get Data in Columns
data["temp"]

0    12
1    14
2    15
3    14
4    21
5    22
6    24
Name: temp, dtype: int64

In [11]:
data.temp

0    12
1    14
2    15
3    14
4    21
5    22
6    24
Name: temp, dtype: int64

In [12]:
type(data.temp)

pandas.core.series.Series

In [13]:
# Get Data in Row
monday = data[data.day == "Monday"]
monday

      day  temp condition
0  Monday    12     Sunny

In [14]:
monday_temp = monday.temp[0]
monday_temp

12

In [15]:
monday_temp_F = monday_temp * 9/5 + 32
monday_temp_F

53.6

In [16]:
temp_list = data["temp"].to_list()
temp_list

[12, 14, 15, 14, 21, 22, 24]

In [17]:
# Average temp
sum(temp_list)/len(temp_list)

17.428571428571427

In [18]:
data.temp.mean()

17.428571428571427

In [19]:
data.temp.where(data.temp > 20, -data.temp)

0   -12
1   -14
2   -15
3   -14
4    21
5    22
6    24
Name: temp, dtype: int64

In [20]:
# Create Dictionary from DataFrame
data.to_dict()

{'day': {0: 'Monday',
  1: 'Tuesday',
  2: 'Wednesday',
  3: 'Thursday',
  4: 'Friday',
  5: 'Saturday',
  6: 'Sunday'},
 'temp': {0: 12, 1: 14, 2: 15, 3: 14, 4: 21, 5: 22, 6: 24},
 'condition': {0: 'Sunny',
  1: 'Rain',
  2: 'Rain',
  3: 'Cloudy',
  4: 'Sunny',
  5: 'Sunny',
  6: 'Sunny'}}

In [21]:
data.to_dict('records')

[{'day': 'Monday', 'temp': 12, 'condition': 'Sunny'},
 {'day': 'Tuesday', 'temp': 14, 'condition': 'Rain'},
 {'day': 'Wednesday', 'temp': 15, 'condition': 'Rain'},
 {'day': 'Thursday', 'temp': 14, 'condition': 'Cloudy'},
 {'day': 'Friday', 'temp': 21, 'condition': 'Sunny'},
 {'day': 'Saturday', 'temp': 22, 'condition': 'Sunny'},
 {'day': 'Sunday', 'temp': 24, 'condition': 'Sunny'}]

In [22]:
# Create DataFrame from Scratch
data_dict = {
    "students": ["Amy", "James", "Angela"],
    "scores": [76, 56, 65],
}
data = pd.DataFrame(data_dict)
data

  students  scores
0      Amy      76
1    James      56
2   Angela      65

In [23]:
data.to_csv("data/new_data.csv")

#### The Great Squirrel Census Data Analysis
#### https://data.cityofnewyork.us/Environment/2018-Central-Park-Squirrel-Census-Squirrel-Data/vfnx-vebw/about_data

In [50]:
squirrel_data = pd.read_csv("data/2018_Central_Park_Squirrel_Data.csv")

squirrel_data["Primary Fur Color"]

0            NaN
1           Gray
2       Cinnamon
3           Gray
4            NaN
          ...
3018        Gray
3019        Gray
3020        Gray
3021        Gray
3022    Cinnamon
Name: Primary Fur Color, Length: 3023, dtype: object

In [54]:
grey_squirrels = squirrel_data[squirrel_data["Primary Fur Color"] == "Gray"]
grey_squirrels

,X,Y,Unique Squirrel ID,Hectare,Shift,Date,Hectare Squirrel Number,Age,Primary Fur Color,Highlight Fur Color,...,Kuks,Quaas,Moans,Tail flags,Tail twitches,Approaches,Indifferent,Runs from,Other Interactions,Lat/Long
1,-73.957044,40.794851,37E-PM-1006-03,37E,PM,10062018,3,Adult,Gray,Cinnamon,...,False,False,False,False,False,False,False,True,me,POINT (-73.9570437717691 40.794850940803904)
3,-73.975725,40.769703,5D-PM-1018-05,05D,PM,10182018,5,Juvenile,Gray,NaN,...,False,False,False,False,False,False,False,True,NaN,POINT (-73.9757249834141 40.7697032606755)
5,-73.956570,40.790256,33H-AM-1019-02,33H,AM,10192018,2,Juvenile,Gray,Cinnamon,...,False,False,False,False,False,False,False,False,NaN,POINT (-73.9565700386162 40.7902561000937)
6,-73.971974,40.769305,6G-PM-1020-02,06G,PM,10202018,2,Adult,Gray,NaN,...,False,False,False,False,False,False,True,False,NaN,POINT (-73.9719735582476 40.7693045133578)
7,-73.960261,40.794288,35C-PM-1013-03,35C,PM,10132018,3,NaN,Gray,Cinnamon,...,False,False,False,False,False,False,False,True,NaN,POINT (-73.9602609920814 40.79428830455661)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3016,-73.966290,40.784330,23C-AM-1019-01,23C,AM,10192018,1,Adult,Gray,"Cinnamon, White",...,True,False,False,False,False,False,True,False,NaN,POINT (-73.9662895079734 40.7843300758044)
3018,-73.963943,40.790868,30B-AM-1007-04,30B,AM,10072018,4,Adult,Gray,NaN,...,False,False,False,False,False,False,False,True,NaN,POINT (-73.9639431360458 40.7908677445466)
3019,-73.970402,40.782560,19A-PM-1013-05,19A,PM,10132018,5,Adult,Gray,White,...,False,False,False,False,False,False,True,False,NaN,POINT (-73.9704015859639 40.7825600069973)
3020,-73.966587,40.783678,22D-PM-1012-07,22D,PM,10122018,7,Adult,Gray,"Black, Cinnamon, White",...,False,False,False,False,False,False,True,False,NaN,POINT (-73.9665871993517 40.7836775064883)
3021,-73.963994,40.789915,29B-PM-1010-02,29B,PM,10102018,2,NaN,Gray,"Cinnamon, White",...,False,False,False,False,False,False,True,False,NaN,POINT (-73.9639941227864 40.7899152327912)

In [68]:
grey_squirrels_count = len(grey_squirrels)
red_squirrels_count = len(squirrel_data[squirrel_data["Primary Fur Color"] == "Cinnamon"])
black_squirrels_count = len(squirrel_data[squirrel_data["Primary Fur Color"] == "Black"])
grey_squirrels_count, red_squirrels_count, black_squirrels_count

(2473, 392, 103)

In [72]:
data_dict = {
    "Fur Color": ["Gray", "Cinnamon", "Black"],
    "Count": [grey_squirrels_count, red_squirrels_count, black_squirrels_count],
}
data_dict

{'Fur Color': ['Gray', 'Cinnamon', 'Black'], 'Count': [2473, 392, 103]}

In [76]:
df = pd.DataFrame(data_dict)
# df.to_csv("data/squirrels_count.csv")
df

  Fur Color  Count
0      Gray   2473
1  Cinnamon    392
2     Black    103